/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import org.example.database.DatabaseConnection
import org.example.database.DatabaseManager  
import org.example.database.DatabaseUtils

fun main() {
    println("🏦 Iniciando Billetera Virtual")
    println("=" * 50)
    
    try {
        // Mostrar información de la conexión
        println("🔗 ${DatabaseConnection.getConnectionInfo()}")
        println("📊 Estado de conexión: ${if (DatabaseConnection.isConnectionActive()) "Activa" else "Inactiva"}")
        
        // Verificar salud de la base de datos
        println("\n🏥 Verificando salud de la base de datos...")
        val isHealthy = DatabaseUtils.checkDatabaseHealth()
        
        if (!isHealthy) {
            println("❌ La base de datos tiene problemas. Verifica que todas las tablas existan.")
            return
        }
        
        // Mostrar resumen detallado
        println()
        DatabaseUtils.showDatabaseSummary()
        
        // Insertar datos de prueba si no existen
        println("\n🧪 Verificando datos de prueba...")
        DatabaseUtils.insertTestData()
        
        // Ejemplo de uso del DatabaseManager
        println("\n🔍 Ejemplos de uso del DatabaseManager:")
        demonstrateUsage()
        
        println("\n🎉 Sistema inicializado correctamente")
        
    } catch (e: Exception) {
        println("❌ Error iniciando el sistema: ${e.message}")
        e.printStackTrace()
    } finally {
        // Cerrar conexión al finalizar
        DatabaseConnection.closeConnection()
    }
}

/**
 * Función para demostrar el uso del DatabaseManager
 */
private fun demonstrateUsage() {
    val dbManager = DatabaseManager()
    
    try {
        // Ejemplo 1: Contar usuarios
        val userCount = dbManager.countRecords("users")
        println("👥 Total de usuarios: $userCount")
        
        // Ejemplo 2: Verificar si existe un email específico
        val emailExists = dbManager.exists("users", "email = ?", "juan@test.com")
        println("📧 ¿Existe juan@test.com? ${if (emailExists) "Sí" else "No"}")
        
        // Ejemplo 3: Obtener información de usuarios (solo si hay datos)
        if (userCount > 0) {
            println("\n👤 Primeros usuarios registrados:")
            val resultSet = dbManager.executeQuery("SELECT full_name, email FROM users LIMIT 3")
            
            var count = 1
            while (resultSet.next()) {
                val name = resultSet.getString("full_name")
                val email = resultSet.getString("email")
                println("   $count. $name ($email)")
                count++
            }
            resultSet.close()
        }
        
        // Ejemplo 4: Contar transacciones por estado
        val completedTransactions = dbManager.countRecords("transactions", "status = ?", "COMPLETED")
        val pendingTransactions = dbManager.countRecords("transactions", "status = ?", "PENDING")
        
        println("\n💸 Transacciones:")
        println("   ✅ Completadas: $completedTransactions")
        println("   ⏳ Pendientes: $pendingTransactions")
        
        // Ejemplo 5: Mostrar balance total del sistema
        showSystemBalance(dbManager)
        
    } catch (e: Exception) {
        println("❌ Error en demostración: ${e.message}")
    }
}

/**
 * Función para mostrar el balance total del sistema
 */
private fun showSystemBalance(dbManager: DatabaseManager) {
    try {
        val resultSet = dbManager.executeQuery("SELECT SUM(balance) as total FROM accounts")
        
        if (resultSet.next()) {
            val totalBalance = resultSet.getDouble("total")
            println("💰 Balance total del sistema: $totalBalance ARS")
        }
        resultSet.close()
        
    } catch (e: Exception) {
        println("⚠️ No se pudo calcular el balance total: ${e.message}")
    }
}

/**
 * Extensión para repetir strings (similar a Python)
 */
private operator fun String.times(n: Int): String = this.repeat(n)