/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import java.sql.Connection
import java.sql.DriverManager

fun main() {
    println("🏦 Iniciando Billetera Virtual")
    
    try {
        // Conectar a la base de datos
        val connection = DriverManager.getConnection("jdbc:sqlite:database/billetera.db")
        
        println("✅ Conexión a base de datos establecida")
        
        // Verificar que las tablas existen
        val tablas = listOf("users", "accounts", "transactions")
        
        tablas.forEach { tabla ->
            val stmt = connection.createStatement()
            val rs = stmt.executeQuery("SELECT COUNT(*) as count FROM $tabla")
            rs.next()
            val count = rs.getInt("count")
            println("📊 Tabla '$tabla': $count registros")
            rs.close()
            stmt.close()
        }
        
        connection.close()
        println("🎉 Sistema inicializado correctamente")
        
    } catch (e: Exception) {
        println("❌ Error al conectar con la base de datos: ${e.message}")
        println("💡 Asegúrate de ejecutar './gradlew setupDatabase' primero")
    }
}